name: 'Add to PYTHONPATH'
description: 'Add specified paths to PYTHONPATH for all supported OS'
inputs:
  path:
    description: 'Path to be added to PYTHONPATH'
    required: true

runs:
  using: "composite"
  steps:
    - name: Add to PYTHONPATH on Linux or macOS
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      shell: bash
      run: echo "PYTHONPATH=${{ inputs.path }}:$PYTHONPATH" >> $GITHUB_ENV

    - name: Add to PYTHONPATH on Windows
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: echo "PYTHONPATH=${{ inputs.path }};$env:PYTHONPATH" | Out-String | Add-Content -Path $env:GITHUB_ENV
