# https://docs.codecov.com/docs/pull-request-comments
comment: false

# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    project:
      default: false # disable the default status that measures entire project